### ISSUE TITLE
How to incorporate "for" loops into commands

### ISSUE THREAD

**Issue by michaelofrancis** [calvinmfloyd/grobblR#11]
Hello, first of all great software. Since these commands can get pretty long, it would be useful to be able to use a for loop in the creation of the grob_row(grob_col etc... 

I tried doing this and the output looks correct (i.e. $ :Classes 'grob_layout', 'R6' <grob_layout>.....) but it is not working with the grob_to_pdf command. An example on how to do this would be helpful.

Thanks!

**Comment by calvinmfloyd** [comment]
Sorry, Michael, just seeing this now. Thanks for reaching out!

Could you provide some reproducible example code and what you would want the output to be? Just so I can understand what the exact problem is. I'm a little unclear on what you're asking.

**Comment by michaelofrancis** [comment]
Hey Calvin, I've already solved my problem by using lots and lots of lines of code. The question is referring to being able to use loops and lists to create the grob layouts as opposed to having to create them individually.....does that make sense?

**Comment by calvinmfloyd** [comment]
I think I understand. If you put all the grob layouts within a list, you can then put that list within `grob_to_pdf()` and it'll put all the grob layouts on separate pages.

Here's a quick example:
```R
library(grobblR)

gl_list = list()

for (i in 1:5) {
  
  gl_list[[i]] = grob_layout(grob_row(grob_col(LETTERS[i])))
  
}

grob_to_pdf(gl_list, file_name = "test.pdf")
```

Does that answer your question? And if it does, should I make that more clear in the documentation somewhere?
