### ISSUE TITLE
special characters

### ISSUE THREAD

**Issue by mmoralesIG** [calvinmfloyd/grobblR#6]
Hi, we are working on delivering small reports to users, in spanish.
I noticed that whenever a special character is used, such as á, é, ñ,
the system crashed

How can I solve this issue?

**Comment by calvinmfloyd** [comment]
Hello,

Thanks for reaching out! Can you provide a reproducible example?

When I run 
```R
library(grobblR)
df = data.frame(
  v1 = c(1, 4, 6),
  v2 = c(3, 1, 1),
  v3 = c("á", "é", "ñ")
  )
df %>% grob_matrix() %>% view_grob()
```
I get the output
![image](https://user-images.githubusercontent.com/29410624/94626178-90053400-0288-11eb-9cac-5c2ce9d7e13d.png)

Same when I save it to a PDF.

**Comment by mmoralesIG** [comment]
I think I just figured it out

I had something like this

grob_col(
      border = FALSE,
      p=9,
      "título",
      aes_list = ga_list(text_align = "center")
    )

which crashed my R, but then I recalled the grob_text
grob_col(
      border = FALSE,
      p=9,
      grob_text("título"),
      aes_list = ga_list(text_align = "center")
    )

It works without grob_text, but if it includes special characters, it crashes. 
So I guess that's it
Still learning and testing

**Comment by calvinmfloyd** [comment]
Interesting. We'll look into it! Thanks again for reaching out.
